In [ ]:
import numpy as np
try:
  del print
except NameError:
  pass

a = np.array([10, 20, 30, 40, 50])

print(a)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data type:", a.dtype)

[10 20 30 40 50]
Shape: (5,)
Size: 5
Data type: int64


In [ ]:
a = np.arange(1, 13).reshape(3, 4)
print(a)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(np.zeros(5))
print(np.ones(5))
print(np.eye(3))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a = np.arange(10, 51, 2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
a = np.linspace(0, 1, 10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[12 24 35]
[ 8 16 25]
[ 20  80 150]
[5. 5. 6.]


In [ ]:
a = np.array([1, 2, 3, 4, 5])

print("Square:", a ** 2)
print("Cube:", a ** 3)

Square: [ 1  4  9 16 25]
Cube: [  1   8  27  64 125]


In [ ]:
a = np.array([100, 200, 300])

a = a * 1.15
print(a)

[115. 230. 345.]


In [ ]:
a = np.array([10, 50, 30])
b = np.array([20, 40, 35])

print("Maximum:", np.maximum(a, b))
print("Minimum:", np.minimum(a, b))

Maximum: [20 50 35]
Minimum: [10 40 30]


In [ ]:
a = np.arange(21)

print("First 5:", a[:5])
print("Last 5:", a[-5:])
print("Index 5 to 15:", a[5:16])
print("Every second:", a[::2])

First 5: [0 1 2 3 4]
Last 5: [16 17 18 19 20]
Index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]
Every second: [ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
a = np.arange(10)
a[:5] = 100

print(a)

[100 100 100 100 100   5   6   7   8   9]


In [ ]:
a = np.array([1, 2, 3, 4, 5])

view = a[:3]
copy = a[:3].copy()

view[0] = 100
copy[1] = 200

print("Original:", a)
print("View:", view)
print("Copy:", copy)


Original: [100   2   3   4   5]
View: [100   2   3]
Copy: [  1 200   3]


In [ ]:
a = np.array([1, 2, 3, 4, 5])

print(a[::-1])

[5 4 3 2 1]


In [ ]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [ ]:
print("Second row:", a[1])
print("Third column:", a[:, 2])
print("Element 50:", a[1, 1])

Second row: [40 50 60]
Third column: [30 60 90]
Element 50: 50


In [ ]:
print(a[:2, 1:])

[[20 30]
 [50 60]]


In [ ]:
a = np.arange(1, 13).reshape(3, 4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a = np.arange(1, 11).reshape(2, 5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
a = np.arange(1, 13).reshape(3, 4)

print(a.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
a = np.arange(24).reshape(2, 3, 4)

print("Original:\n", a)
print("Transpose:\n", a.transpose())
print("Swap axes:\n", a.swapaxes(0, 2))

Original:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Transpose:
 [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
Swap axes:
 [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([[9,8,7], [6,5,4], [3,2,1]])

print("Addition:\n", a + b)
print("Multiplication:\n", a * b)

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

print(np.dot(a, b))

[[19 22]
 [43 50]]


In [ ]:
a = np.array([[1,2], [3,4]])

t = a.T

print("Transpose:\n", t)
print("Dot product:\n", np.dot(t, a))

Transpose:
 [[1 3]
 [2 4]]
Dot product:
 [[10 14]
 [14 20]]


In [ ]:
a = np.array([1, 4, 9, 16, 25])

print(np.sqrt(a))

[1. 2. 3. 4. 5.]


In [ ]:
a = np.array([1, 2, 3])

print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
a = np.random.randn(5)

print("Array:", a)
print("Square root:", np.sqrt(np.abs(a)))
print("Exponential:", np.exp(a))
print("Absolute:", np.abs(a))

Array: [ 1.51537914  0.12256447  0.85207263 -1.20684132 -0.47320015]
Square root: [1.23100737 0.35009209 0.9230778  1.0985633  0.68789545]
Exponential: [4.5511463  1.130392   2.34450111 0.29914068 0.62300537]
Absolute: [1.51537914 0.12256447 0.85207263 1.20684132 0.47320015]


In [ ]:
a = np.random.rand(5)
b = np.random.rand(5)

print(np.maximum(a, b))

[0.76716164 0.20073341 0.42178242 0.83150496 0.96825255]


In [ ]:
marks = np.array([35, 72, 48, 90, 55, 28])

result = np.where(marks < 40, 0, marks)

print(result)

[ 0 72 48 90 55  0]


In [ ]:
income = np.array([30000, 60000, 45000, 80000])

result = np.where(income >= 50000, "High", "Low")

print(result)

['Low' 'High' 'Low' 'High']


In [ ]:
a = np.array([10, 25, 35, 40, 20])

a = np.where(a > 30, 100, a)

print(a)

[ 10  25 100 100  20]


In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Variance:", np.var(a))
print("Standard deviation:", np.std(a))

Sum: 45
Mean: 5.0
Variance: 6.666666666666667
Standard deviation: 2.581988897471611


In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Row sum:", np.sum(a, axis=1))
print("Column sum:", np.sum(a, axis=0))

Row sum: [ 6 15 24]
Column sum: [12 15 18]


In [ ]:
marks = np.array([55, 67, 45, 89, 72, 60, 40, 91, 76, 58])

print("Mean:", np.mean(marks))
print("Standard deviation:", np.std(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))

Mean: 65.3
Standard deviation: 16.199074047611486
Minimum: 40
Maximum: 91


In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Row sum:", np.sum(a, axis=1))
print("Column sum:", np.sum(a, axis=0))

Row sum: [ 6 15 24]
Column sum: [12 15 18]


In [ ]:
marks = np.array([55, 67, 45, 89, 72, 60, 40, 91, 76, 58])

print("Mean:", np.mean(marks))
print("Standard deviation:", np.std(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))

Mean: 65.3
Standard deviation: 16.199074047611486
Minimum: 40
Maximum: 91


In [ ]:
a = np.array([True, True, False])

print("Any:", np.any(a))
print("All:", np.all(a))

Any: True
All: False


In [ ]:
a = np.array([1,2,2,3,4,4,5,5,5])
print(np.unique(a))

[1 2 3 4 5]


In [ ]:
marks = np.array([50,60,50,70,80,60,90,70])

print(np.unique(marks))

[50 60 70 80 90]


In [ ]:
a = np.array([10,20,30,40,50])
selected = np.array([20,50,70])
print(np.isin(selected,a))

[ True  True False]


In [ ]:
marks = np.array([[60,70,80],
                  [40,45,50],
                  [75,80,85],
                  [30,35,40],
                  [55,60,65],
                  [90,85,95],
                  [45,50,55],
                  [70,65,75],
                  [35,40,45],
                  [80,75,85],
                  ])
total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
print("Total:", total)
print("Average:", average)
print("Students with average >= 50:")
print(np.where(average >= 50)[0])


Total: [210 135 240 105 180 270 150 210 120 240]
Average: [70. 45. 80. 35. 60. 90. 50. 70. 40. 80.]
Students with average >= 50:
[0 2 4 5 6 7 9]


In [ ]:
a = np.arange(1,17).reshape(4,4)
print("Matrix:\n", a)
print("Transpose:\n", a.T)
print("Row sums:", np.sum(a, axis=1))
print("Column sums:", np.sum(a, axis=0))
print("Maximum:", np.max(a))
print("Minimum:", np.min(a))
print("Central 2x2:\n", a[1:3, 1:3])

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row sums: [10 26 42 58]
Column sums: [28 32 36 40]
Maximum: 16
Minimum: 1
Central 2x2:
 [[ 6  7]
 [10 11]]


In [ ]:
a = np.random.randn(20)
print("Data:", a)
print("Mean:", np.mean(a))
print("Standard deviation:", np.std(a))
print("Minimun:", np.min(a))
print("Maximum:", np.max(a))
print("Sorted:", np.sort(a))
result = np.where(a<0, 0,a)
print("Negative replaced by 0:", result)

Data: [-0.03748789  2.18171497 -0.43254218  0.3801284  -0.9702525  -0.40891562
 -0.57912914  1.01347962 -1.56828249 -0.0506847   0.72442336 -0.44239669
  0.239124   -0.25533349  2.00529377  1.23158212 -0.39701119  0.61814469
 -2.18581161  1.52449293]
Mean: 0.12952681904613955
Standard deviation: 1.0888754110658903
Minimun: -2.1858116083636
Maximum: 2.181714972645762
Sorted: [-2.18581161 -1.56828249 -0.9702525  -0.57912914 -0.44239669 -0.43254218
 -0.40891562 -0.39701119 -0.25533349 -0.0506847  -0.03748789  0.239124
  0.3801284   0.61814469  0.72442336  1.01347962  1.23158212  1.52449293
  2.00529377  2.18171497]
Negative replaced by 0: [0.         2.18171497 0.         0.3801284  0.         0.
 0.         1.01347962 0.         0.         0.72442336 0.
 0.239124   0.         2.00529377 1.23158212 0.         0.61814469
 0.         1.52449293]


In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b= np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])
addition = a+b
Multiplication = a * b
